#! /bin/env bash

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Start polybar for each monitor
for m in $(polybar --list-monitors | cut -d":" -f1); do
    if xrandr | grep primary | grep -q "$m"; then
        type=full
    else
        type=simple
    fi
    MONITOR=$m polybar --reload $type &
done
