#! /bin/env bash

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Start polybar for each monitor
MONITORS=$(polybar --list-monitors | cut -d":" -f1)

for m in $MONITORS; do
    if [ "$(echo "$MONITORS" | wc -l)" = 1 ]; then
        # show full polybar if there is only one monitor (this also handles mirrored monitors)
        type=full
    elif xrandr | grep primary | grep -q "$m"; then
        # show full polybar on primary monitor
        type=full
    else
        # show simple polybar on all additional monitors
        type=simple
    fi
    MONITOR=$m polybar --reload $type &
done
